# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digits', models.CharField(max_length=8)),
                ('balance', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digits', models.CharField(max_length=6)),
                ('balance', models.PositiveSmallIntegerField()),
                ('used', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('price', models.PositiveSmallIntegerField()),
                ('image', models.URLField()),
            ],
        ),
    ]
