# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='digits',
            field=models.CharField(default='049ad610', max_length=8),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='digits',
            field=models.CharField(default='99502e', max_length=6),
        ),
    ]
