# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20170725_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='digits',
            field=models.CharField(default='c4aeb3dd', max_length=8),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='digits',
            field=models.CharField(default='50e29c0fb7', max_length=10),
        ),
    ]
