# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 00:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20170802_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='movement_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to=settings.AUTH_USER_MODEL),
        ),
    ]
