# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20170725_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='balance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
