# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20170725_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='http://lorempixel.com/600/400/sports/1/'),
        ),
    ]
