# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20170726_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='http://lorempixel.com/240/240/technics/'),
        ),
    ]
