# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('type', models.BooleanField()),
                ('amount', models.SmallIntegerField()),
                ('fkcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Card')),
            ],
        ),
    ]
