# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_movement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='amount',
            new_name='m_amount',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='fkcard',
            new_name='m_cardm_card',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='desc',
            new_name='m_desc',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='type',
            new_name='m_type',
        ),
    ]
