# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 18:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20170729_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movement',
            options={'get_latest_by': 'm_date'},
        ),
        migrations.AddField(
            model_name='movement',
            name='m_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
