# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20170729_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(default=payment.models.card_digit_gen),
        ),
    ]
