# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_card_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='m_amount',
            new_name='movement_amount',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='m_cardm_card',
            new_name='movement_card',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='m_date',
            new_name='movement_date',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='m_desc',
            new_name='movement_desc',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='m_type',
            new_name='movement_type',
        ),
    ]
