# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_auto_20170729_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='digits',
            field=models.CharField(default='7b311300', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(default='7b311300'),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='balance',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
