# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_auto_20170729_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='digits',
            field=models.CharField(default='8a07d3c5', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(default='8a07d3c5'),
        ),
    ]
