# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_auto_20170730_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='digits',
            field=models.CharField(default='06059eea', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(default='06059eea'),
        ),
    ]
