# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_auto_20170731_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='digits',
            field=models.CharField(default='190ba5c9', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(default='190ba5c9'),
        ),
    ]
