# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_auto_20170731_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='slug',
        ),
        migrations.AlterField(
            model_name='card',
            name='digits',
            field=models.CharField(default=payment.models.card_digit_gen, max_length=8, unique=True),
        ),
    ]
